project/messages/forms.py
 #project/messages/forms.py

from flask_wtf import Form
from wtforms import DateField, IntegerField, TextAreaField, StringField

from wtforms.validators import DataRequired

class AddMessageForm(Form):
    message_id = IntegerField()
    message_type = StringField('Task Name')
    message = TextAreaField('Blog message', validators=[DataRequired()])
    
    status = IntegerField('Status')

project/projects/forms.py
 #project/projects/forms.py

from flask_wtf import Form
from wtforms import DateField, IntegerField, TextAreaField, StringField

from wtforms.validators import DataRequired

class AddProjectForm(Form):
    project_id = IntegerField()
    project_name = StringField('Project Name')
    project_desc = TextAreaField('Project Desc', validators=[DataRequired()])
    status = IntegerField('Status')

project/tasks/forms.py
#project/tasks/forms.py

from flask_wtf import Form
from wtforms import StringField, DateField, IntegerField, SelectField

from wtforms.validators import DataRequired

class AddTaskForm(Form):
    task_id = IntegerField()
    name = StringField('Task Name', validators=[DataRequired()])
    due_date = DateField(
    'Date Due (mm/dd/yyyy)',
    validators=[DataRequired()], format='%m/%d/%Y'
    )
    priority = SelectField(
    'Priority',
    validators=[DataRequired()],
    choices=[
    ('1','1'),('2','2'),('3','3'),('4','4'),('5','5'),('6','6'),('7','7'),('8','8'),('9','9'),('10','10'),
    ]
    )

    status = IntegerField('Status')

project/messages/views.py
# project/messages/views.py

import datetime
from functools import wraps
from flask import flash, redirect, render_template, request, session, url_for, Blueprint

from sqlalchemy.sql import table, column
from .forms import AddMessageForm

from project import db
from project.models import Message

##############
### config ###
##############

messages_blueprint = Blueprint('messages', __name__)

###############
### helpers ###
###############

def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
          return test(*args, **kwargs)
        else:
          flash('You need to login first.')
          return redirect(url_for('users.login'))
    return wrap

###############
### routes ####
###############

@messages_blueprint.route('/')
def allmessages():
    form = AddMessageForm(request.form)
    all_messages = db.session.query(Message).order_by(Message.message_type.desc()).all()
    return render_template(
      'messages.html',
      entries=all_messages,
      form = form
    )

@messages_blueprint.route('/newmessage/', methods=['GET','POST'])
@login_required
def new_message():
    error = None
    form = AddMessageForm(request.form)
    if request.method == 'POST':
      if form.validate_on_submit():
        new_message = Message(
          form.message.data,
          form.message_type.data,
          session['user_id']
        )
        db.session.add(new_message)
        db.session.commit()
        flash('New entry was successful.')
        return redirect(url_for('messages.allmessages'))

project/projects/views.py
# project/projects/views.py

import datetime
from functools import wraps
from flask import flash, redirect, render_template, request, session, url_for, Blueprint

from sqlalchemy.sql import table, column
from .forms import AddMessageForm

from project import db
from project.models import Message

##############
### config ###
##############

projects_blueprint = Blueprint('projects', __name__)

###############
### helpers ###
###############

def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
          return test(*args, **kwargs)
        else:
          flash('You need to login first.')
          return redirect(url_for('users.login'))
    return wrap

###############
### routes ####
###############

@projects_blueprint.route('/')
def main_page():
      return render_template(
        'index.html'
      )

@projects_blueprint.route('/snippets')
def allmessages():
    form = AddMessageForm(request.form)
    all_messages = db.session.query(Message).order_by(Message.message_type.desc()).all()
    return render_template(
      'messages.html',
      entries=all_messages,
      form = form
    )

@projects_blueprint.route('/newproject/', methods=['GET','POST'])
@login_required
def new_message():
    error = None
    form = AddMessageForm(request.form)
    if request.method == 'POST':
      if form.validate_on_submit():
        new_message = Message(
          form.message.data,
          form.message_type.data,
          session['user_id']
        )
        db.session.add(new_message)
        db.session.commit()
        flash('New entry was successful.')
        return redirect(url_for('messages.allmessages'))

project/tasks/views.py
# project/tasks/views.py

import datetime
from functools import wraps
from flask import flash, redirect, render_template, request, session, url_for, Blueprint

from .forms import AddTaskForm
from project import db
from project.models import Task

##############
### config ###
##############

tasks_blueprint = Blueprint('tasks', __name__)

###############
### helpers ###
###############

def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
          return test(*args, **kwargs)
        else:
          flash('You need to login first.')
          return redirect(url_for('users.login'))
    return wrap


def get_tasks(status):
    return db.session.query(Task).filter_by(status=status).order_by(Task.due_date.asc())

def open_tasks():
    return db.session.query(Task).filter_by(status="1").order_by(Task.due_date.asc())

def closed_tasks():
    return db.session.query(Task).filter_by(status="0").order_by(Task.due_date.asc())
###############
### routes ####
###############

@tasks_blueprint.route('/tasks/')
@login_required
def tasks():
    form = AddTaskForm(request.form)
    open_tasks_dataset = db.session.query(Task).filter_by(status="1").order_by(Task.due_date.asc())
    closed_tasks_dataset = db.session.query(Task).filter_by(status="0").order_by(Task.due_date.asc())
    return render_template(
        'tasks.html',
        form=form,
        open_tasks=open_tasks_dataset,
        closed_tasks=closed_tasks_dataset,
        username = session['user_name']
    )

@tasks_blueprint.route('/add/', methods=['GET', 'POST'])
@login_required
def new_task():
    error = None
    form = AddTaskForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
          new_task_obj = Task(
            form.name.data,
            form.due_date.data,
            form.priority.data,
            datetime.datetime.utcnow(),
            '1',
            session['user_id']
          )
          db.session.add(new_task_obj)
          db.session.commit()
          flash('New entry was successful.')
          return redirect(url_for('tasks.tasks'))

    return render_template(
      'tasks.html',
      form=form,
      error=error,
      open_tasks=get_tasks('1'),
      closed_tasks=get_tasks('0')
      )



@tasks_blueprint.route('/complete/<int:task_id>/')
@login_required
def complete(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == 'admin':
        task.update({"status": "0"})
        db.session.commit()
        flash("The task is complete. Nicely done.")
        return redirect(url_for('tasks.tasks'))
    else:
        flash("Unauthorized. You can only update your tasks. Duh.")
        return redirect(url_for('tasks.tasks'))

@tasks_blueprint.route('/delete/<int:task_id>/')
@login_required
def delete_entry(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == "admin":
        task.delete()
        db.session.commit()
        flash("The task was deleted.")
        return redirect(url_for('tasks.tasks'))
    else:
        flash("You can only delete your tasks. Nimrod.")
        return redirect(url_for('tasks.tasks'))

project/users/views.py
#project/users/views.py

###############
### imports ###
###############

from functools import wraps
from flask import flash, redirect, render_template, \
  request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError

from .forms import RegisterForm, LoginForm
from project import db, bcrypt
from project.models import User

###############
### config  ###
###############

users_blueprint = Blueprint('users', __name__)


###############
### helpers ###
###############

def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
      if 'logged_in' in session:
        return test(*args, **kwargs)
      else:
        flash('You need to login first, nimrod.')
        return redirect(url_for('users.login'))
    return wrap

###############
### routes  ###
###############

@users_blueprint.route('/all_users/')
@login_required
def allusers():
    all_users = db.session.query(User).all()
    return render_template(
        'all_users.html',
        all_users=all_users,
        username = session['user_name']
    )

@users_blueprint.route('/logout/')
@login_required
def logout():
    session.pop('logged_in', None)
    session.pop('user_id', None)
    session.pop('role', None)
    session.pop('user_name', None)

    flash('Goodbye')
    return redirect(url_for('users.login'))

@users_blueprint.route('/login/', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
      if form.validate_on_submit():
        user = User.query.filter_by(name=request.form['name']).first()
        if user is not None and bcrypt.check_password_hash(user.password,request.form['password']):
          session['logged_in'] = True
          session['user_id'] = user.id
          session['role'] = user.role
          session['user_name'] = user.name
          user_name = session['user_name']

          pretty_user_name = user_name.capitalize()
          session['pretty_user_name'] = pretty_user_name
          login_msg = 'Welcome, ' + pretty_user_name
          flash(login_msg)
          return redirect(url_for('tasks.tasks'))
        else:
          error = 'Invalid credentials.'
    return render_template('login.html', form=form, error=error)

@users_blueprint.route('/register/', methods=['GET','POST'])
def register():
    error=None
    form = RegisterForm(request.form)

    if request.method == 'POST':

        if form.validate_on_submit():
            new_user = User(
            form.name.data,
            form.email.data,
            bcrypt.generate_password_hash(form.password.data),
            )

            try:
                db.session.add(new_user)
                db.session.commit()
                flash('Thanks for registering. Login!')
                return redirect(url_for('users.login'))
            except IntegrityError:
                error = 'That username or email exists.'
                return render_template('register.html',form=form, error=error)
    return render_template('register.html', form=form, error=error)

project/templates/_base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>[wlk stuff]</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/yeti/bootstrap.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">

    <body>
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle"
              data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle Nav</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">wlk</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('messages.allmessages') }}">Snippets</a></li>
                <li><a href="##">Projects [coming]</a></li>
                <li><a href="{{ url_for('tasks.tasks') }}">Tasks</a></li>

                <!--<li><a href="{{ url_for('users.allusers') }}">Users</a></li>-->
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if session.logged_in %}
                <li><a>Sup, {{ session['pretty_user_name'] }}</a></li>
                <li><a href="/logout">SIGNOUT</a></li>
              {% else %}
              <li><a href="/register">SIGN-UP</a></li>
                <li><a href="/login">LOGIN</a></li>
            {% endif %}
              </ul>
          </div><!--/.nav-collapse-->
        </div>
      </div>

      <div class="container">
        <div class="content">
          {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
          {% endfor %}

          {% if error %}
            <div class="error"><strong>Error:</strong> {{ error }} </div>
          {% endif %}

          {% block content %}
          {% endblock %}

        </div>

        <div class="footer">
          <p>&copy; <a href="https://www.realpython.com">Real Python (rules!)</a></p>
          
        </div>
      </div><!--/.container-->

      <script src="//code.jquery.com/jquery-1.11.4.min.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
      <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    </body>
  </html>

project/templates/all_users.html
{% extends "_base.html" %}
{% block content %}

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Role</th>
  </tr>

  {% for user in all_users %}
  <tr>
    <td>{{ user.name }}</td>
    <td>{{ user.email }}</td>
    <td>{{ user.role }}</td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

project/templates/index.html
{% extends "_base.html" %}

{% block content %}

<h1>Main Page</h1>
<div class="container">

  <div class="row" style="border:1px solid red;">
    <div class="col-md-4 cmd41">One
    </div>
    <div class="col-md-4">Two
    </div>
    <div class="col-md-4">Three
    </div>
  </div>
</div>

{% endblock %}

project/templates/login.html
{% extends "_base.html" %}

{% block content %}

  <h1>Welcome to FlaskTaskr.</h1>
  <h3>Please sign in to access your task list.</h3>

  <form class="form-signin" role="form" method="post" action="/login/">
    {{ form.csrf_token }}
    <p>
      {{ form.name(placeholder="name") }}
        {% if form.name.errors %}
          <span class="error">
            {% for error in form.name.errors %}
              {{ error }}
            {% endfor %}
          </span>
        {% endif %}
    </p>
    <p>
      {{ form.password(placeholder="password") }}
        {% if form.password.errors %}
          <span class="error">
            {% for error in form.password.errors %}
              {{ error }}
            {% endfor %}
          </span>
        {% endif %}
    </p>

    <p>
      <button class="btn btn-sm btn-success" type="Submit">Sign in</button>
    </p>
  </form>

  <p>
    <em>Need an account?</em>&nbsp;&nbsp;<a href="/register">Sign up!!</a>
  </p>

{% endblock %}

project/templates/messages.html
{% extends "_base.html" %}

{% block content %}

<div class="container">
  <div class="jumbotron">
    <h1>Snippets</h1>
  </div>
{% if session.logged_in %}
  <div class="add-message">
    <h3>Add a new snippet:</h3>
    <form action="{{ url_for('messages.new_message') }}" method="POST">
      {{ form.csrf_token }}
    <p>
      {{ form.message_type(placeholder="Type") }}
      <br /><br />
      {{ form.message(placeholder="Snippet code", cols="75", rows="10") }} 
        {% if form.message.errors %}
        <span class="error">
          {% for error in form.message.errors %}
            {{ error }}
          {% endfor %}
        </span>
        {% endif %}
    </p>

    <p><input class="btn btn-default" type="submit" value="Submit" /></p>
    </form>
  </div>
{% endif %}

  {% for entry in entries %}
        {% if entry.message_type %}
    <p>
      <h3>
        {{ entry.message_type }}
        
    </h3> 
        {{entry.message}}
  </p>
        {% endif %}
  {% endfor %}
</div>
{% endblock %}
<script>
$(function() {

});
</script>

project/templates/projects.html
{% extends "_base.html" %}

{% block content %}

<div class="container">
{% if session.logged_in %}
  <div class="add-message">
    <h3>Add a new project:</h3>
    <form action="{{ url_for('projects.new_project') }}" method="POST">
      {{ form.csrf_token }}
    <p>
      {{ form.project_type(placeholder="Type") }}
      <br /><br />
      {{ form.project_type(placeholder="Project", cols="75", rows="10") }} 
        {% if form.project_type.errors %}
        <span class="error">
          {% for error in form.project_type.errors %}
            {{ error }}
          {% endfor %}
        </span>
        {% endif %}
    </p>

    <p><input class="btn btn-default" type="submit" value="Submit" /></p>
    </form>
  </div>
{% endif %}
</div>
{% endblock %}
<script>
$(function() {

});
</script>

project/templates/register.html
{% extends "_base.html" %}

{% block content %}

<h1>Welcome to FlaskTaskr.</h1>
<h3>Please register to access the task list.</h3>

<form method="POST" action="/register/">
{{ form.csrf_token }}
<p>
  {{ form.name(placeholder="name") }}
  {% if form.name.errors %}
    <span class="error">
      {% for error in form.name.errors %}
        {{ error }}
      {% endfor %}
    </span>
  {% endif %}
</p>

<p>
  {{ form.email(placeholder="email address") }}
  {% if form.email.errors %}
    <span class="error">
      {% for error in form.email.errors %}
        {{ error }}
      {% endfor %}
    </span>
  {% endif %}
</p>

<p>
  {{ form.password(placeholder="password") }}
  {% if form.password.errors %}
    <span class="error">
      {% for error in form.password.errors %}
        {{ error }}
      {% endfor %}
    </span>
  {% endif %}
</p>

<p>
  {{ form.confirm(placeholder="confirm password") }}

  {% if form.confirm.errors %}
    <span class="error">
      {% for error in form.confirm.errors %}
        {{ error }}
      {% endfor %}
    </span>
  {% endif %}
</p>

<p>
  <button class="btn btn-sm btn-success" type="submit">Register</button>
  <br />
  <em>Already registered?</em>&nbsp; Click <a href="/">here</a> to sign in.</p>
</form>

{% endblock %}

project/templates/tasks.html
{% extends "_base.html" %}
{% block content %}
<div class="add-task">
  <h3>Add a task:</h3>

  <form action="{{ url_for('tasks.new_task') }}" method="POST">
    {{ form.csrf_token }}
  <p>
    {{ form.name(placeholder="name") }}
      {% if form.name.errors %}
      <span class="error">
        {% for error in form.name.errors %}
          {{ error }}
        {% endfor %}
      </span>
      {% endif %}
  </p>
  <p>
    {{ form.due_date(placeholder="due date") }}
      {% if form.due_date.errors %}
        <span class="error">
          {% for error in form.due_date.errors %}
            {{ error }}
          {% endfor %}
        </span>
      {% endif %}
  </p>

  <p>
    {{ form.priority.label }}
    {{ form.priority }}
      {% if form.priority.errors %}
        <span class="error">
          {% for error in form.priority.errors %}
            {{ error }}
          {% endfor %}
        </span>
      {% endif %}
  </p>

  <p><input class="btn btn-default" type="submit" value="Submit" /></p>
</form>

</div>
<div class="entries">
  <br>
  <br>
  <h2>Open tasks:</h2>
  <div class="datagrid">
    <table>
      <thead>
        <tr>
          <th width="200px"><strong>Task Name</strong></th>
          <th width="90px"><strong>Due Date</strong></th>
          <th width="100px"><strong>Posted Date</strong></th>
          <th width="50px"><strong>Priority</strong></th>
          <th width="90px"><strong>Posted By</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for task in open_tasks %}
        <tr>
          <td width="200px">{{ task.name }}</td>
          <td width="90px">{{ task.due_date.strftime('%d-%m-%Y') }}</td>
          <td width="100px">{{ task.posted_date.strftime('%d-%m-%Y') }}</td>
          <td width="50px">{{ task.priority }}</td>
          <td width="90px">{{ task.poster.name }}</td>
          <td>
            {% if task.poster.name == session.name or session.role == "admin" %}
              <a href="{{ url_for('tasks.delete_entry', task_id = task.task_id) }}">Delete</a>  -
              <a href="{{ url_for('tasks.complete', task_id = task.task_id) }}">Mark as Complete</a>
            {% else  %}
            <span>N/A</span>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <br>
  <br>
</div>
<div class="entries">
  <h2>Closed tasks:</h2>
  <div class="datagrid">
    <table>
      <thead>
        <tr>
          <th width="200px"><strong>Task Name</strong></th>
          <th width="75px"><strong>Due Date</strong></th>
          <th width="100px"><strong>Posted Date</strong></th>
          <th width="50px"><strong>Priority</strong></th>
          <th width="90px"><strong>Posted By</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for task in closed_tasks %}
        <tr>
          <td width="200px">{{ task.name }}</td>
          <td width="75px">{{ task.due_date }}</td>
          <td width="100px">{{ task.posted_date }}</td>
          <td width="50px">{{ task.priority }}</td>
          <td width="90px">{{ task.poster.name }}</td>
        <td>
            {% if task.poster.name == session.name or session.role == "admin" %}
              <a href="{{ url_for('tasks.delete_entry', task_id = task.task_id) }}">Delete</a>
            {% else  %}
            <span>N/A</span>
            {% endif %}
        </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>

{% endblock %}